### ISSUE TITLE
Notification alerts window needs some love

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#101]
![alerts](https://cloud.githubusercontent.com/assets/778890/5272014/6cd1a10a-7a79-11e4-81e6-7d7d39a5aefd.png)

OK, here is the notification window. It needs some love:
1) Add link to the user profile (click on username)
2) Make time and date pretier - smaller (maybe you can put this under the name)
3) Add a "cross" to every alert to delete it (ajax is needed, so maybe in myalerts 2.1)
4) Make link to the thread blue one and clickable
5) Add support for own format of date and time---it ignores my setting in mybb!!!
6) Make avatars smaller
7) Is it scrollable if you have a lot of alerts?

**Comment by euantorano** [comment]
I'm postponing these fixes until v2.0.1 in the interest of releasing the core v2.0.0 soon.

**Comment by Cu8eR** [comment]
@euantorano - OK, amazing, Thx for v2.0. I hope that v2.1.0 will be there much sooner than we hope :) 

This issue is related to:
#111 #122

**Comment by euantorano** [comment]
Yep, there shouldn't be such a long wait now that I've finished University hopefully :smile:

**Comment by Cu8eR** [comment]
Congratulations! I know that feeling :)

**Comment by Cu8eR** [comment]
@euantorano - I think that the notification - "No alerts to display" should be centered in modal window. Now it is aligned to the left side

**Comment by euantorano** [comment]
Yep, it was in the drop down but I obviously forgot for the modal.
