### ISSUE TITLE
Alert Link Displays Blank Page

### ISSUE THREAD

**Issue by jnschrag** [MyBBStuff/MyAlerts#105]
I didn't see this bug posted anywhere else, so my apologies if this is a duplicate.

When an alert is created, the default link that goes with it is: http://mysite.com/alerts.php?action=view&id=#

When I try and go to that link, with # being the ID number of the alert, it displays a blank page. This happens with every alert ID number that I test. This error happens everywhere that format of link is created.

One suggestion would be to have those alerts go to alerts.php?#ID. So it would go to an anchor rather than a separate page just to display that single alert.

**Comment by euantorano** [comment]
All fixed :)

**Comment by jnschrag** [comment]
Fantastic! Thanks for all your hard work.
