### ISSUE TITLE
Subscribed Threads

### ISSUE THREAD

**Issue by Tbo29** [MyBBStuff/MyAlerts#109]
When replying to a subscribed thread the message is from myalerts_post_threadauthor and not from
myalerts_subscribed_thread.
On line 20 in SubscribedThreadFormatter you use   $this->lang->myalertsrow_subscribed, but this is missing in the language file.

Also in plugin myalerts.php shouldn't the subscribed alert be registered like:

new MybbStuff_MyAlerts_Formatter_SubscribedThreadFormatter($mybb, $lang, 'subscribed_thread'));

(I modified the myalertsrow_subscribed to suscribed_thread) and added the alert to the plugin. Now I have it working with the correct message.

**Comment by ozanakkaya** [comment]
thanks tbo :)

**Comment by euantorano** [comment]
Fixed, thanks!
