### ISSUE TITLE
Change unread -> read alert when user visit the post

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#110]
http://community.mybb.com/thread-127444-post-1129447.html#pid1129447

@Shade-

**Comment by Shade-** [comment]
Thank you for the reminder, but since I am still studying for my exams, this won't happen for a while.

**Comment by Cu8eR** [comment]
@Shade- I understand - so good luck in exams :+1:

**Comment by euantorano** [comment]
This issue exists for almost all alert types, and I will be aiming to fix it in MyAlerts 2.1.0.

**Comment by Cu8eR** [comment]
This is one of the most wanted feature for 2.1.0. Many users on my board are really happy that we have working notification system, BUT they complain about this - every alerts must be deleted manually. 

My idea - after click on the new alert -> mark them as read and delete it from popup window (or whatever).

@euantorano - keep good work! thank you!

**Comment by Eldenroot** [comment]
@lairdshaw - this one is a game changer :) for now my users complain that they are overhelmed by new notifications and when they visit a post with alert, the alert is still marked as unread... so they just do not wanna use this feature. I had to disable alrt type for new replies on my board. What do you think, is this possible to implement?

**Comment by lairdshaw** [comment]
@Eldenroot, yep, this would be a good one to implement. Re your above comment from Jun 7, 2015, I don't see how we could delete it from the popup window, but maybe we could implement a new option (link) for the modal: "Hide read alerts".  What do you think?

**Comment by Eldenroot** [comment]
Yes, at least this option
