### ISSUE TITLE
Templates to change

### ISSUE THREAD

**Issue by WhiteNeo** [MyBBStuff/MyAlerts#114]
You have to change templates i know you have more work and it's not easy to review all, and i found some lesser errors but can serve to all of our :dancers: 

FIrst at all rename scripts to another name, like js_popup i rename it because it marks a potencial risk by MyBB and it's for the name, even i use this code inside it:

&lt;script type="text/javascript"&gt;
    var unreadAlerts = "{$mybb->user['unreadAlerts']}";
&lt;/script&gt;
&lt;script type="text/javascript" src="{$mybb->asset_url}/jscripts/myalerts.js"&gt;&lt;/script&gt;

Another one is alert_row_popup

&lt;tr class="alert {$alert['alert_status']} alert--{$alert['alert_code']}" id="alert_row_popup_{$alert['id']}"&gt;
&lt;td class="{$altbg}" class="align-center alert__avatar" align="center"&gt;

You can see its a double class inside td, i change to this value

&lt;tr class="alert {$alert['alert_status']} alert--{$alert['alert_code']}" id="alert_row_popup_{$alert['id']}"&gt;
&lt;td class="{$altbg} alert__avatar align="center"&gt;

I think the class can do all job and don not have to redeclare align and one class in this way have to work fine, i know is a typo error only but i review this excelente mod and i want to cooperate at least on some things i can do.

I help another users to customize it and to make it work on his forums, but i found this and i think you have to know it >D i have some other things like ull request but i make it when i remember it

**Comment by euantorano** [comment]
Thanks for the report. I'll look into both of these :+1:

**Comment by euantorano** [comment]
Bumping this to remind myself to fix it!

**Comment by euantorano** [comment]
Fixed, thanks!
