### ISSUE TITLE
Alerts too big

### ISSUE THREAD

**Issue by nollidnosnhoj** [MyBBStuff/MyAlerts#117]
For some reason, the alerts section is too big. I don't know if it's a theme problem or not, but I think it's a theme problem.

![Issue](http://i.imgur.com/ZOJzgfJ.png)

**Comment by WhiteNeo** [comment]
Yes indeed is a problem with your theme, because MyAlerts take customized areas on your theme, so you have to set another classes and styles to set a better visualization.

It's only a theme design problem, not MyAlerts.

**Comment by euantorano** [comment]
Hi,

Sorry for the late response. As @WhiteNeo said, this is an issue with your theme that will require CSS edits.
