### ISSUE TITLE
Reaching a new PM from source other then the MyAlerts alert doesn't automatically mark the alert as read.

### ISSUE THREAD

**Issue by Neurovert** [MyBBStuff/MyAlerts#118]
After reading new PM through "Private Messages" or through link sent on e-mail, the MyAlerts alert stays as new one - in the count of alerts and in the dropdown table. 

If this is possible, it would be nice if MyAlerts would check wheter u had already read a PM and then it would automatically mark the alert as read/old. 

This of course relates to all types of alerts, but I think it's most needed in the PM notification case. Let me know if this is too much work to make it.

**Comment by euantorano** [comment]
This is planned for the future, but the first priority is to finish 2.0.0 and get it released. This will likely be impossible lamented in 2.1.0.
