### ISSUE TITLE
warning when viewing plugin page

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/MyAlerts#119]
Euan,

When I go to my plugins page to activate the latest development version of this plugin, I'm met with the following warning on the page:

Warning [2] require_once(/inc/plugins/MybbStuff/Core/ClassLoader.php): failed to open stream: No such file or directory - Line: 22 - File: inc/plugins/myalerts.php PHP 5.3.10-1ubuntu3.15 (Linux)

![126 apr 26](https://cloud.githubusercontent.com/assets/2748980/7335899/5c9c6cda-ebac-11e4-8c16-941f8f6a6e6b.jpg)

when browsing through the files, there is no /Core folder within /inc/plugins/MybbStuff:

![127 apr 26](https://cloud.githubusercontent.com/assets/2748980/7335904/c9575362-ebac-11e4-9753-053bdb4d19c8.jpg)

**Comment by euantorano** [comment]
Hi,

You need [Plugins.Core](https://github.com/MyBBStuff/Plugins.Core) for MyAlerts too. I've obviously forgot to include that in the documentation. When the final release arrives, it'll all be bundled as a single download.

**Comment by andrewjs18** [comment]
works fine after installing Plugins.Core.

thanks!
