### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by ozanakkaya** [MyBBStuff/MyAlerts#120]
1-)...\inc\plugins\MybbStuff\MyAlerts\src\Formatter\SubscribedThreadFormatter.php

line:20

            $this->lang->myalertsrow_subscribed,

this is incorrect code

correct code is,

            $this->lang->myalerts_subscribed_thread,

2-)inc\plugins\myalerts.php

line 850

correct code:
    $alertType = MybbStuff_MyAlerts_AlertTypeManager::getInstance()->getByCode('subscribed_thread');

**Comment by euantorano** [comment]
Fixed in 9c653b.
