### ISSUE TITLE
Avatar alt atribute on modal box missing.

### ISSUE THREAD

**Issue by WhiteNeo** [MyBBStuff/MyAlerts#129]
Only a missing value on this, i add on line 511of myalerts plugin file this content:

		$outputAlert['username'] = htmlspecialchars_uni($fromUser['username']);

before this value

        $outputAlert['message'] = $formatter->formatAlert($alertToParse, $outputAlert);

And done, because take a missing value changed on formatter i think, but username was taken for alt atribute on img insde the aert_row template and i dunno aanywhere else, but this fix that little thing.

**Comment by euantorano** [comment]
Thanks, I'll fix that tonight :)

**Comment by euantorano** [comment]
Fixed.
