### ISSUE TITLE
Normal user´s name doesnt follow style of username group in popup window

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#130]
User "Chmura" belongs to normal usergroup (registered users) - his name should be blue, but it is black... this problem occurs only for users which has default mybb style for username

![bug](https://cloud.githubusercontent.com/assets/778890/8019793/ed26edaa-0c60-11e5-9c9c-1aeb3bb219ef.png)

**Comment by euantorano** [comment]
Strange. Are normal users configured on your board to have a blue username? If so, it should work but I will have to investigate.

**Comment by Cu8eR** [comment]
OK, I uploaded latest version, install on fresh MyBB and now it is OK - text is blue and it works fine
![bug2](https://cloud.githubusercontent.com/assets/778890/8023674/f01073dc-0d15-11e5-9991-92950363bc6f.png)
