### ISSUE TITLE
mark all alerts as read

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/MyAlerts#133]
it'd be nice if we could have an option to mark all of the alerts as being read without having to visit each alert and/or delete all of them.

**Comment by euantorano** [comment]
Agreed, I'll do this for 2.1.0.

**Comment by Cu8eR** [comment]
@euantorano - I understand that you have a lot of work, but please it would be great to release v 2.1.0 soon with all bugfixes mentioned in MyBB forum thread. I have been waiting really long :(

**Comment by euantorano** [comment]
Yep, I'll release it soon.

**Comment by Vioner** [comment]
@euantorano I myself would prefer to have not only ability to mark all alerts as read, but also individual ones.
Example:
You open the alerts popup -> see few new popups, literally read them, then you mark as read the ones that you don't want to visit right now, but maybe later, you'd review all alerts and come back to this one. I hope this is clear.

For now I've added the delete option in the popup and it works, but mark as read also would be very helpful. 

But ofc this is not a must-have - automatic mark as read is top priority for me.

**Comment by euantorano** [comment]
@Vioner that is planned for, eventually. I'm also going to add the delete button to the modal to make life easier. Right now the easiest way to mark an alert read is to click on it or to load the alerts page - both of which kind of suck.

**Comment by Cu8eR** [comment]
@euantorano - any ETA? MyAlerts is one of the best and a must have plugin for MyBB 1.8. Why? Because MyBB 1.8 unfortunately has no inbuild core alerts system (which other boards have)... Thank you very much for your time and this plugin.

**Comment by euantorano** [comment]
No ETA at the minute. I'm trying to work on 2.0 too which needs more work right now.

**Comment by Cu8eR** [comment]
@euantorano - I understand. However MyBB 2.0 will be there in final version next year... there should be proper working and maintained MyAlerts plugin for MyBB 1.8.x branch. I hope you will find some time to release at least a bugfix version with some improvements mentioned in issues here. Thank you, have a nice day ;)

**Comment by Cu8eR** [comment]
@Vioner - could you please share your code for deleting alerts in popup? thank you

**Comment by Eldenroot** [comment]
@euantorano maybe just a pure html link in a modal or/and in alert page to "Mark all as read", is that now possible?

**Comment by euantorano** [comment]
Yep, should be I believe.
