### ISSUE TITLE
Delete alert if thread, post, PM, etc. no longer exists

### ISSUE THREAD

**Issue by jnschrag** [MyBBStuff/MyAlerts#134]
This might be related to #121, but is a slightly different request.

It would be great if MyAlerts would delete any related alerts when a thread, post, PM, etc. are deleted. For example, on my forum we have a maintenance thread that all staff members are alerted to when there are new posts. Right now, if another staff member handles the request and deletes the post, I will still have the "new reply" alert. Clicking on the alert will take me to the maintenance thread, but if there are no posts, it can be a little confusing. There's also no point in having alerts for thread or posts that don't exist anymore.

I think this enhancement could work by hooking into the delete functionality of myBB. When a thread or post is being deleted, the object_id of the alert and the type of alert can be checked to determine if it should be deleted or not.

The PMs are a little trickier, and might not be necessary, but having this functionality for the thread and posts would be really helpful.

**Comment by euantorano** [comment]
It's kind of related, and I'll definitely look into it for 2.1.0.
