### ISSUE TITLE
1.8.5 Compatibility?

### ISSUE THREAD

**Issue by mrmaiko** [MyBBStuff/MyAlerts#138]
Are there any plans for it?

**Comment by euantorano** [comment]
MyAlerts already works with MyBB 1.8.5...

**Comment by mrmaiko** [comment]
Is there documentation on how? As it seems that PluginLIbrary only works
with 1.6

**Comment by euantorano** [comment]
Grab PluginLibrary from here: https://github.com/frostschutz/MyBB-PluginLibrary

The 1.8 version is only on GitHub as far as I know.

**Comment by mrmaiko** [comment]
Thank you!
