### ISSUE TITLE
Add default settings for alerts types

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#141]
Now we can globally disable every alert type, enable by default, but what about to enable the alert for users but keep it inactive until users changed it in UCP?

**Comment by euantorano** [comment]
So it's allowed to be enabled, but is disabled by default? I suppose so. I'll do this for 2.1.0.

**Comment by Cu8eR** [comment]
Yes! Thx!

**Comment by Eldenroot** [comment]
![image](https://github.com/MyBBStuff/MyAlerts/assets/778890/5f7a3326-495c-4d89-9094-9b552f11f590)

@lairdshaw maybe add a new column here (default status - enabled/disabled)

**Comment by lairdshaw** [comment]
@Eldenroot, that seems suitable, yes, but it's low on my priority list. I'm happy though for you or anybody else to implement it in the meantime.

**Comment by Eldenroot** [comment]
I understand, but imagine this situation:

You use extended alerts pack and you do not want to overwhelm the users with aall type of alerts... but you wanna provide the possibility :)
