### ISSUE TITLE
apostrophes are not being parsed

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/MyAlerts#142]
if a thread title has an apostrophe in it, myalerts does not parse it correctly, like so:

![wxxrsy1](https://cloud.githubusercontent.com/assets/2748980/8270768/fc4e87be-17c0-11e5-9f4f-1ee6931b675b.jpg)

**Comment by Cu8eR** [comment]
I just test it on my board and it is related to my Thank you/like plugin. I dont know what is wrong but I have to check it later.

![bugb](https://cloud.githubusercontent.com/assets/778890/8270883/2c421c7c-17fa-11e5-89ff-fb6fc8da734f.png)

**Comment by andrewjs18** [comment]
good catch.

**Comment by WhiteNeo** [comment]
That was an fixed error due some core additions on MyAlerts 2.0.2, but fixed on some systems i review for MyAlerts bridge with.

FIxed on TYL System and Thank You MyBB System, it's not a MyAlerts problem at all.

**Comment by euantorano** [comment]
As this doesn't seem to be a problem in MyAlerts, closing this.
