### ISSUE TITLE
Issue with github code (2.0.3)

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#143]
I got this error with latest code from github (I just wanted to test it before release :)  on my test board. I also updated plugins core from your github,

![bug](https://cloud.githubusercontent.com/assets/778890/8270804/b545cbd6-17f5-11e5-81ec-f4f990852c4c.png)

**Comment by euantorano** [comment]
Ah, oops. I'll fix that today

**Comment by euantorano** [comment]
Fixed.
