### ISSUE TITLE
Show absolute date and time on hover in popup window

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#145]
It would be amazing if we can see time and date on mouse hover in popup window - now we can see only Today, Yesterday, XX hours but we cannot see absolute time - so hover on the date it would show tooltip with absolute date and time

just title="" would be enough

![reguest](https://cloud.githubusercontent.com/assets/778890/8270847/032706ba-17f8-11e5-9dcf-adff55e74932.png)

EDIT: unfortunately mouse cursor is invisible, it is pointing to the first row

**Comment by Cu8eR** [comment]
I know - MyBB 1.8 uses relative time format, but it would be a nice addition - sometimes it is quite useful to know when the notification arrived. Not just see 10x today :)

**Comment by euantorano** [comment]
I thought it was already in on hover, but I'll check and add it if not.

**Comment by Cu8eR** [comment]
Unfortunately it is not here :(

**Comment by labrocca** [comment]
I agree with this and an alert on an active forum doesn't help if it says "Today" everywhere. Members want to know 1 hour ago or something like that.  It's much more preferred how far back it was to TIME_NOW.

**Comment by Eldenroot** [comment]
This one and https://github.com/MyBBStuff/MyAlerts/issues/260 and https://github.com/MyBBStuff/MyAlerts/issues/262 is super annoying :)

**Comment by Eldenroot** [comment]
@lairdshaw - hmm, it is weird - it displays date and time when the alerts is older or not?

**Comment by lairdshaw** [comment]
I'm not sure exactly what you're asking, @Eldenroot, but I think that the solution to this issue is to change this line:
https://github.com/MyBBStuff/MyAlerts/blob/4ba7999cd86f59d1c3fefffb873514e0cb5c9815/inc/plugins/myalerts.php#L680
to
```php
			'relative',
```
Let us know if that achieves what you want.

**Comment by euantorano** [comment]
Really it would be ideal if the core handled this in some way - either with a core generic template for dates/times or something like that. That way the format would be the same everywhere. On 30 Aug 2023, at 21:24, Eldenroot ***@***.***> wrote:﻿
Nope, this is still valid - it should display a title (mouse hover) when you have "today" relative time... because it is not accurate and useles.

**Comment by lairdshaw** [comment]
> Nope, this is still valid

Yep, I wasn't denying that.

> it should display a title (mouse hover) when you have "today" relative time

That's what the replacement I suggested achieves. Did you try it? If it works for you too, then it can be filed as a PR resolving this issue.

**Comment by lairdshaw** [comment]
> Really it would be ideal if the core handled this in some way - either with a core generic template for dates/times or something like that. That way the format would be the same everywhere.

The 'relative' format respects the user's date format setting - per his/her UserCP preferences - for non-relative display, i.e., the on-hover tooltip, and date+times further back in the past. To me, that seems satisfactory, but I'm curious as to the template approach that you suggest.

**Comment by Eldenroot** [comment]
I think it is not working as intended - it displays "Today" ... not 15 minutes ago etc.

Moreover on mouse hover you should be able to view exact (no relative) time stamp of the alert (we use this for Thank you/like system).

**Comment by lairdshaw** [comment]
> I think it is not working as intended - it displays "Today" ... not 15 minutes ago etc.
> 
> Moreover on mouse hover you should be able to view exact (no relative) time stamp of the alert (we use this for Thank you/like system).

My guess is that you didn't actually apply the change that I suggested above: https://github.com/MyBBStuff/MyAlerts/issues/145#issuecomment-1698419860

Please apply and let us know whether it resolves your concern. If so, we can create a PR with that change.

**Comment by lairdshaw** [comment]
Any update on this, @Eldenroot?

**Comment by Eldenroot** [comment]
Please, send me your screenshot of the modal window with alerts after this change. Also for a new (recent) alerts- Thank you!
