### ISSUE TITLE
Clicking on delete button in recent alerts tab makes other alerts hiden

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#146]
When you have more read alerts in recent alerts tab and you click on "delete" -> notification - no alerts to display. 
![buga1](https://cloud.githubusercontent.com/assets/778890/8270881/072cbc58-17fa-11e5-8392-8e0ae3114c45.png)

But when you hit F5 now - list is updated and you can see other alerts
![bugb](https://cloud.githubusercontent.com/assets/778890/8270882/09316be8-17fa-11e5-8386-23388d815639.png)

**Comment by Cu8eR** [comment]
Still bugged - it is in UCP - click on "Delete" -> everything diaspear :(

**Comment by WhiteNeo** [comment]
That is a js error i fixed it on my own repo, i forgot it but it's a easy one to fix and the first thing i fixed xD.

I did not know how to use github so i can not sent in right ways patches to Euan T.

But this is fixed on my own repo as otger additions.

**Comment by Cu8eR** [comment]
@WhiteNeo - I made a PR with your code and a note that all credits go to you :)

**Comment by euantorano** [comment]
Thanks, I knew it would be an easy fix :)
