### ISSUE TITLE
Change color of read alerts

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#148]
If you have more alerts, it is a little bit tricky to know which of them hasnt been read already and which hasnt been. What about to change color for them in popup or make an icon which indicates their status?

**Comment by euantorano** [comment]
Could be a good idea. IIRC, there should be a CSS class already on them so I can just dim them or something.

**Comment by Cu8eR** [comment]
Yes, at least this... maybe icons would be good too.

**Comment by Cu8eR** [comment]
.alert--read.alert {
  opacity: .5;
}

.alert.alert--read td.trow1 {
  background-color: #FAEACC;
}

**Comment by euantorano** [comment]
Sounds like a fairly good baseline. I'll add that, thanks!
