### ISSUE TITLE
Installation of this plugin:

### ISSUE THREAD

**Issue by stephencovell** [MyBBStuff/MyAlerts#149]
MyBB Internal Error

MyBB has experienced an internal error and cannot continue.

Error Type:
    Catchable Fatal Error (4096)
Error Message:
    Argument 4 passed to MybbStuff_MyAlerts_AlertManager::createInstance() must be an instance of pluginSystem, instance of MybbStuff_MyAlerts_AlertTypeManager given, called in website../inc/plugins/myalerts.php on line 724 and defined
Location:
    File: inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php
    Line: 145
Code:
    142.         MyBB $mybb,
    143.         DB_Base $db,
    144.         datacache $cache,
    145.         pluginSystem $plugins,
    146.         MybbStuff_MyAlerts_AlertTypeManager $alertTypeManager
    147.     ) {
    148.         if (static::$instance === null) { 
Backtrace:
    File 	Line 	Function
    /inc/class_error.php 	207 	errorHandler->output_error
    /inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php 	145 	errorHandler->error
    /inc/plugins/myalerts.php 	724 	MybbStuff_MyAlerts_AlertManager::createInstance
    /inc/plugins/myalerts.php 	696 	myalerts_create_instances
    /inc/class_plugins.php 	139 	myalerts_global_start
    /global.php 	99 	pluginSystem->run_hooks
    /index.php 	18 	require_once

and this is the error I get from my admin control pannel:

MyBB Internal Error

MyBB has experienced an internal error and cannot continue.

Error Type:
    Catchable Fatal Error (4096)
Error Message:
    Argument 4 passed to MybbStuff_MyAlerts_AlertManager::createInstance() must be an instance of pluginSystem, instance of MybbStuff_MyAlerts_AlertTypeManager given, called inwebsite../inc/plugins/myalerts.php on line 724 and defined
Location:
    File: inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php
    Line: 145
Backtrace:
    File 	Line 	Function
    /inc/class_error.php 	207 	errorHandler->output_error
    /inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php 	145 	errorHandler->error
    /inc/plugins/myalerts.php 	724 	MybbStuff_MyAlerts_AlertManager::createInstance
    /inc/class_plugins.php 	139 	myalerts_create_instances
    /admin/index.php 	697 	pluginSystem->run_hooks

Yes, This is a fresh install of myBB. Site: www.nw-gaming.com. Any help to resolve this issue would be much appreciated.

**Comment by euantorano** [comment]
This is because you're using the development version. Use the stable version from the tags: https://github.com/MyBBStuff/MyAlerts/releases
