### ISSUE TITLE
Avatar problem in posts

### ISSUE THREAD

**Issue by Damianoseczek** [MyBBStuff/MyAlerts#150]
Maximum width and height of avatars is 150x150 on my forum. 
When I don't have any alerts - avatars are displayed at max 150x150 pixels.
But when I have for example PM alert from 'User1' and this alert still exists, his avatar in post is displayed in 50x50 pixels (this is the setting of MyAlerts). After deleting this alert - his avatar is again in 150x150. 

I hope that you understand.
Greetings.

**Comment by euantorano** [comment]
Hi,

This is a bug with MyBB. Are you using MyBB 1.8.5? It should be fixed in that version I believe.

**Comment by Damianoseczek** [comment]
I'm using 1.8.4, becouse translation to my language (Polish) isn't finished yet.

So if it's MyBB bug, you can close this issue. 
Thank you. :)
