### ISSUE TITLE
New alerts in red

### ISSUE THREAD

**Issue by MauricioCr** [MyBBStuff/MyAlerts#151]
I add this in my global.css:

.alerts.alerts--new{
    color: red !important;
    font-weight: bold;
} 

The font-weight work fine, but the color no!

![1](https://cloud.githubusercontent.com/assets/5367731/8291585/b67fd06c-18e7-11e5-9a0c-1dadea94ac4f.png)

http://community.mybb.com/thread-171301-post-1165431.html#pid1165431

My forum: www.fotonaturaleza.net/foro

**Comment by euantorano** [comment]
Hi,

This really depends on your theme you might need to add an "a" selector to change the link colour.

**Comment by MauricioCr** [comment]
Thanks, my theme is the default

**Comment by MauricioCr** [comment]
Worked it with:

.alerts.alerts--new a{
    color: red !important;
    font-weight: bold;
}
