### ISSUE TITLE
Load language in User CP (Custom alert)

### ISSUE THREAD

**Issue by MauricioCr** [MyBBStuff/MyAlerts#152]
Hi!

How to load the language in User CP

![alert](https://cloud.githubusercontent.com/assets/5367731/8437251/2448cc8c-1f1b-11e5-8004-c86da439765f.png)

In /inc/languages/english/photos.lang.php I have this:

$l['myalerts_setting_photo_voted'] = "Receive alert for voted photo?";
$l['myalerts_setting_photo_liked'] = "Receive alert for liked photo?";

The rest works well only in the User CP is not loaded language

Thanks!

**Comment by euantorano** [comment]
Hi,

Are "photo_liked" and "photo_voted" the `code` for your custom alert types? Also, have you hooked in to `myalerts_load_lang` to make sure your language file is loaded?

**Comment by MauricioCr** [comment]
I solved adding $lang->load('photos', false, true); in $plugins->add_hook('global_start', 'register_formatters');

Thanks
