### ISSUE TITLE
Change unread alert colour

### ISSUE THREAD

**Issue by katosdev** [MyBBStuff/MyAlerts#153]
Hi there!

My apologies if this is a simple question but I am rather confused as to how to change the colour of unread alerts. I have got:

.newAlerts > a {
    color: red !important;
}

however the alerts don't appear red?
This is how they appear: 
http://puu.sh/iLUJk/8e6154b55b.png

What I would like to do is change this text, (and/or number) to be red when there is a new alert that has not been read.

Hope this makes sense,
Katos

**Comment by Cu8eR** [comment]
.alerts.alerts--new a{
    color: red !important;
    font-weight: bold;
}

**Comment by euantorano** [comment]
As above, there are several CSS classes you can use to change the styling.
