### ISSUE TITLE
Clickable Smilies & Text Formatting Stop Working with MyAlerts Enabled

### ISSUE THREAD

**Issue by mattwma** [MyBBStuff/MyAlerts#154]
Hello,

When I enable MyAlerts the clickable smilies window that shows up when you click "New Reply" stops working. Also, the advanced text editing menu that should be above the "Your Message" field disappears.

I'm currently running MyBB 1.8.5, php 5.4.40, MySQLi 5.5.4.2, and MyAlerts 2.0.2 downloaded from Github today, July 8th, 2015.

Any help would be greatly appreciated.

-Matt

**Comment by euantorano** [comment]
Strange, what's your forum URL? Sounds like a JavaScript conflict somewhere, possibly with your theme.

**Comment by mattwma** [comment]
URL: http://community.winemakersacademy.com

Would you like me to re-enable MyAlerts?

**Comment by euantorano** [comment]
Hi,

Yes please.

**Comment by mattwma** [comment]
Ok, it is now enabled.

**Comment by euantorano** [comment]
Hi,

Which browser are you using? I'm using Safari and it seems to be working fine for me.

**Comment by mattwma** [comment]
Currently Chromium. I'll go try Firefox

**Comment by mattwma** [comment]
Ok, I tried it in Firefox and Chrome and it is now working. Perhaps I need to clear my cache in Chromium after upgrading MyAlerts today. Do you think that could clear it up?

**Comment by euantorano** [comment]
It might help, it's certainly worth a try!

**Comment by mattwma** [comment]
Thanks Euan, everything is working now after the MyAlerts upgrade and clearing the cache. I appreciate the work you put into this plugin, and for checking for errors on my community. Sorry to have dragged you through this, next time I'll try the cache first. Cheers!

**Comment by euantorano** [comment]
Not a problem, glad it's sorted :smile:
