### ISSUE TITLE
php error when filtering mod cp warning logs

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/MyAlerts#157]
if you go into your mod cp, click on the warning logs and then filter it, it'll throw a php error in the default theme and in my custom theme.

The following warnings occurred:
Warning [2] urlencode() expects parameter 1 to be string, array given - Line: 677 - File: inc/plugins/myalerts.php PHP 5.5.9

**Comment by euantorano** [comment]
Thanks, I'll look into it.

**Comment by PirataNervo** [comment]
This happens whenever there are array inputs.

```
/**
 * Returns the full current URL.
 *
 * @return string The current URL, including query parameters.
 */
function myalerts_get_current_url()
{
    global $mybb;

    $format = $mybb->settings['bburl'] . '/' . THIS_SCRIPT;

    if (!empty($_GET)) {
        $format .= '?';

        foreach ($_GET as $key => $val) {
            $key = urlencode($key);
            $val = urlencode($val);
            $format .= "{$key}={$val}&";
        }
    }

    $format = rtrim($format, '&');

    return $format;
}
```

The problem is in this function. More specifically here:
```
        foreach ($_GET as $key => $val) {
            $key = urlencode($key);
            $val = urlencode($val);
            $format .= "{$key}={$val}&";
        }
```

**Comment by euantorano** [comment]
Fixed this in the most recent commit I believe, but haven't had a chance to test it.

**Comment by euantorano** [comment]
For reference, the commit that should fix it is 3a3a0b9e

**Comment by euantorano** [comment]
DId either of you have a chance to check if the patch fixed this? @andrewjs18 @PirataNervo?

**Comment by PirataNervo** [comment]
Nope, sorry. I just reported it here because I was developing a plugin for a client and he reported a bug related to this. I used a workaround to get past this in my plugin.

**Comment by euantorano** [comment]
Alright, no problem. I'll test it more.

**Comment by noxwyll** [comment]
Greetngs. I'm the client.
Ya Pirata already fixed it. Otherwise I would test if for you.

**Comment by euantorano** [comment]
Alright, not a problem. I'm fairly sure the patch should fix the problem.

**Comment by andrewjs18** [comment]
@euantorano, I'll test it now...

**Comment by andrewjs18** [comment]
@euantorano, this looks good after manually applying the changes.

**Comment by Cu8eR** [comment]
@euantorano - works fine

**Comment by Eldenroot** [comment]
@lairdshaw this is fixed
