### ISSUE TITLE
Clicking Alerts on Header did some weird things

### ISSUE THREAD

**Issue by nollidnosnhoj** [MyBBStuff/MyAlerts#160]
It is hard to explain what happened, so I capture my monitor to show you what happened.
https://www.youtube.com/watch?v=n7CHFV8vLT4&feature=youtu.be

So when I click the Alerts link on the header....
1. My Private Message Count turns read.
2. the alerts.php page appears on the bottom of the forum index.

I tried editing it where it looks like this when there's a new alert.
http://i.imgur.com/nlPPTsi.png

This is what the alerts.css looks like:
http://pastebin.com/MpnyaXLb

header_welcomeblock_member template:
http://pastebin.com/zWAUXr4h

myalerts_headericon template:
http://pastebin.com/XgvPiunb

**Comment by euantorano** [comment]
That's... weird. Could you PM me on mybb.com with details for a user account (possibly an admin account) so I can debug? I've not seen this one before.

**Comment by nollidnosnhoj** [comment]
I messaged you!

**Comment by euantorano** [comment]
Ok, thanks.
