### ISSUE TITLE
Modal window and overlay z-index

### ISSUE THREAD

**Issue by SvePu** [MyBBStuff/MyAlerts#162]
The modal window and the overlay should get another z-index in inline style.
# myalerts_alerts_modal => z-index:10000;

.jquery-modal.blocker => z-index:9999;

![myalerts_modal_zindex](https://cloud.githubusercontent.com/assets/9826631/10417495/14a49b8e-703e-11e5-8eca-5def1656e5a7.png)

Can't find this part in code, I guess you know where you've to edit. ;)

**Comment by euantorano** [comment]
Ah yes, I'll have to try and add that to the style. The z index in the inline style is applied by the MyBB modal js library.

**Comment by SvePu** [comment]
In older version of myalerts.js was a function for modal window:

```javascript
module.prototype.openModal = function openModal(event) {
	event.preventDefault();

	var originalTarget = $(event.currentTarget),
		modalSelector = originalTarget.attr('data-selector');

	$(modalSelector).modal({
		fadeDuration: 250,
		keepelement: true,
	});

	return false;
};
```
there you could add the z-index definition, like:
```javascript
module.prototype.openModal = function openModal(event) {
	event.preventDefault();

	var originalTarget = $(event.currentTarget),
		modalSelector = originalTarget.attr('data-selector');

	$(modalSelector).modal({
		fadeDuration: 250,
		keepelement: true,
		zIndex: 9999
	});

	return false;
};
```

**Comment by euantorano** [comment]
Yeah, might have to go back to that possibly.

**Comment by Destroy666x** [comment]
> The z index in the inline style is applied by the MyBB modal js library.

It only does automatically if you use MyBB.popupWindow: https://github.com/mybb/mybb/blob/feature/jscripts/general.js#L75 Otherwise you need to include it manually in options: https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L4112

**Comment by SvePu** [comment]
Thx @Destroy666x 

@euantorano Maybe you can add this option to the headericon.html template

**Comment by euantorano** [comment]
Yeah, I’ll look into it. I think it was Omar who submitted a PR for the current code.

**Comment by SvePu** [comment]
The changes were here: https://github.com/MyBBStuff/MyAlerts/commit/5b55aaa04779ec84b13533d7c30d4b5af9d45268#diff-0f7deed7992b0d8b5c6186a753c1799b
