### ISSUE TITLE
I want to old desing

### ISSUE THREAD

**Issue by MemoryHackers** [MyBBStuff/MyAlerts#163]
http://mods.mybb.com/uploads/previews/21114-1349877975-Alerts%20popup.PNG

I like old desing please ı need 

ı not like new desing popup 

thank you

**Comment by MauricioCr** [comment]
+1

**Comment by euantorano** [comment]
Hi, you can change back to the old design by editing the template and JavaScript. I will not be changing the core back as it is too much effort to maintain across themes.
