### ISSUE TITLE
Causing Catchable Fatal Error 

### ISSUE THREAD

**Issue by ccalhounjr** [MyBBStuff/MyAlerts#165]
Error Type:
Catchable Fatal Error (4096)
Error Message:
Argument 1 passed to MybbStuff_MyAlerts_AlertTypeManager::createInstance() must be an instance of DB_Base, instance of DB_MySQLi given, called in /usr/www/shavargo/shavargo/inc/plugins/myalerts.php on line 604 and defined
Location:
File: inc/plugins/MybbStuff/MyAlerts/src/AlertTypeManager.php
Line: 88
Code:
85.      *
86.      * @return MybbStuff_MyAlerts_AlertTypeManager The created instance.
87.      */
88.     public static function createInstance(DB_Base $db, datacache $cache)
89.     {
90.         if (static::$instance === null) {
91.             static::$instance = new self($db, $cache);

**Comment by euantorano** [comment]
What version of MyBB are you using? You need 1.8.5 or newer.

**Comment by ccalhounjr** [comment]
I'm pretty sure its 1.8.1, I'll perform the update now and see what happens.
