### ISSUE TITLE
Dropdown Myalerts?

### ISSUE THREAD

**Issue by hgtucel** [MyBBStuff/MyAlerts#166]
I'm sorry I do not speak English.

Pop-up instead of using dropdown menu how can we use?

**Comment by euantorano** [comment]
Hi,

You'd have to modify the templates and the JavaScript, but I do not provide any support for doing so.

**Comment by hgtucel** [comment]
Hi, (I'm sorry I do not speak English.)

myalerts_headericon the template with which you can check myalerts_modal_content label template codes.??

myalerts_headericon  get myalerts_modal_content?

myalerts_headericon template example;
<ul class="dropdown">
	{$myalerts_modal_content}
</ul>

myalerts_modal_content template

<li>....</li>
<li>...</li>

**Comment by hgtucel** [comment]
Hi, (I'm sorry I do not speak English.)

myalerts_headericon the template with which you can check myalerts_modal_content label template codes.??

myalerts_headericon get myalerts_modal_content?

myalerts_headericon template example;

{$myalerts_modal_content}
myalerts_modal_content template example;

<li>....<li>

<li>...<li>

**Comment by hgtucel** [comment]
@euantorano 
Hi, (I'm sorry I do not speak English.)

myalerts_headericon the template with which you can check myalerts_modal_content label template codes.??

myalerts_headericon get myalerts_modal_content?

myalerts_headericon template example;

{$myalerts_modal_content}
myalerts_modal_content template example;
<li>..
<li>..
