### ISSUE TITLE
Show popup in the right top corner when a new notification arrive

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#173]
Show popup in the right top corner when a new notification arrive - something like MyBB 1.8 does

**Comment by euantorano** [comment]
I don't see much point to this as notifications aren't fetched automatically - only on refresh.

**Comment by Cu8eR** [comment]
I thought there is autorefresh in setting page

**Comment by euantorano** [comment]
Yes, but it only takes effect on the alerts list page as it has always done.

**Comment by Cu8eR** [comment]
OK, nevermind... I am closing
