### ISSUE TITLE
Missing location

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#175]
http://community.mybb.com/thread-171301-post-1203467.html#pid1203467

**Comment by WildcardSearch** [comment]
Noticing this as well since I started auto refreshing alerts...

**Comment by Eldenroot** [comment]
@lairdshaw - what do you think? I think it is working

![image](https://github.com/MyBBStuff/MyAlerts/assets/778890/40191f7e-b1ef-4efe-bb88-eb36891cc76f)

**Comment by lairdshaw** [comment]
@Eldenroot, yep, any WOL problems should have been fixed in #294. Given that you're no longer experiencing problems, I'm closing this issue.
