### ISSUE TITLE
Any reason to use pink color in myalerts popup?

### ISSUE THREAD

**Issue by Cu8eR** [MyBBStuff/MyAlerts#182]
Is there any reason to use "red" color for background for alerts? It should follow MyBB 1.8 default css color for td.trow1 and td.trow2

**Comment by euantorano** [comment]
I can't remember, I'm sure I had some reason when I wrote it

**Comment by Cu8eR** [comment]
You added it here... my code? Maybe typo... https://github.com/MyBBStuff/MyAlerts/commit/ccf62207b9eaf0ebbe7018ec606ea804e01d2570
