### ISSUE TITLE
No alerts type in ACP after uninstall and install again

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#185]
With latest MyAlerts from Github - no alerts types from MyBB (PM, reply, quoete, etc) here

![myalerts](https://cloud.githubusercontent.com/assets/778890/13300969/d15e2bae-db42-11e5-85ae-7529e218d530.png)

**Comment by Cu8eR** [comment]
OK, you have to install and uinstall multiple times to fix this error
