### ISSUE TITLE
Remove unread count when alerts modal is opened

### ISSUE THREAD

**Issue by keithpickering** [MyBBStuff/MyAlerts#188]
Our users are a little confused by the default behavior of myalerts. On most sites with notification windows, the unread number is cleared immediately after the window is opened, since the user is now aware of those alerts. With myalerts, the unread count stays visible until you actually click an alert.

What I'm planning is to make an Ajax request using xmlhttp.php, in order to mark all alerts as read without deleting  them. This seems like the best route but I'm wondering if you think there is a better method.

**Comment by euantorano** [comment]
Hi,

That is the way that it previously behaved, but I got an overwhelming number of complaints about it from people saying that's not what they wanted, so I implemented the current approach. Unfortunately it's difficult to please everybody so I tend to play towards the loudest crowd :wink:

Marking them read via AJAX is probably the best way. The old system would mark them as read when the initial AJAX request to get the modal was fired (marking them as read within `alerts.php`). You'll probably want to clear the actual counter on the page too, though it might not be 0 (another alert may arrive between loading and viewing alerts) so another action may be required on `alerts.php` to get the number of unread alerts.

**Comment by keithpickering** [comment]
Wow, that's really weird that people complained about it working properly. Thanks for the info!

**Comment by euantorano** [comment]
Yep, unfortunately that always seems to be the way of things!

**Comment by keithpickering** [comment]
When was the last time/version where the unread count behaved this way? Do you think I could just reintegrate it from an older release?

**Comment by euantorano** [comment]
The last time was in v1.0.5, but a lot of things changed for 2.0.0, so it would be fairly difficult to copy that code across.

**Comment by Destroy666x** [comment]
I fully agree with you, the current way is unusable since you either need to delete all alerts or open them one by one... I'll be working on a version that lets you mark single/all alerts as read soon.

**Comment by euantorano** [comment]
@Destroy666x that's not really what's being asked here though... The next version will allow you to mark single alerts or all alerts as read. You can already mark all as ready from the UCP as is.

**Comment by Destroy666x** [comment]
It is basically the same thing, it just differs by pressing a "mark all read" link/button instead of doing it fully automatically. Changing the behavior would basically be a matter of moving the event from one element (link) to another (modal/dropdown/whatever).

**Comment by euantorano** [comment]
It's similar, but not exactly the same. It's exactly how it used to work, and as I said above I received a _lot_ of complaints. Probably should have ignored them, but I didn't. I plan to add marking single/all as read for the next version before the end of this month. I have other features I'd like to add too, but may not get them done in time.

**Comment by Destroy666x** [comment]
Looking forward to these changes in that case.

**Comment by keithpickering** [comment]
Yeah, I'll probably just implement it myself, doesn't seem too difficult. I've already edited a ton of myalerts code, so I can't upgrade anyway :p

**Comment by keithpickering** [comment]
Slightly related: how can I keep an alert from being returned using getUnreadAlerts, but still keep it unread? Example: I'm checking every 5 seconds for new alerts using ajax. If I mark the alert as read as soon as it comes in, the unread count won't show after a page refresh. But if I don't mark the alert as read, it will keep coming in every 5 seconds since it's still technically an unread alert. Any ideas? I hope I'm making sense.

**Comment by Cu8eeeR** [comment]
Any progress @keithpickering ?

**Comment by Eldenroot** [comment]
@lairdshaw - the solution would be to add a new "button" (in this case a link) - mark all unread alerts read in a modal window

![image](https://github.com/MyBBStuff/MyAlerts/assets/778890/ac195312-c310-4fc8-91bc-b184b53e2e54)

**Comment by lairdshaw** [comment]
> @lairdshaw - the solution would be to add a new "button" (in this case a link) - mark all unread alerts read in a modal window

Implemented already in #282.

**Comment by Eldenroot** [comment]
OK, you can close then :) thank you
