### ISSUE TITLE
Link redirects to thread instead of post id

### ISSUE THREAD

**Issue by ghost** [MyBBStuff/MyAlerts#191]
Basically, when opening up the alerts modal on the forum, you get to click on the link but it takes you to the original post of the thread, and doesn't pass the get request with the post id in there.

**Comment by euantorano** [comment]
That's interesting, I'll investigate this, thanks.

**Comment by Eldenroot** [comment]
I can confirm this one...unfortunately quite bad in a very large thread with many posts

**Comment by lairdshaw** [comment]
For which alert type?

**Comment by Eldenroot** [comment]
I think it was with a new reply.

**Comment by lairdshaw** [comment]
Can't reproduce. Have tried with:
1. Alerts for "when somebody replies to your thread".
2. Alerts for "when somebody replies to one of your subscribed threads".

Have also tried both of the above with:
1. Default URLs.
2. MyBB core "search engine friendly URLs".
3. Google SEO plugin URLs with:
   1. Default casing ("lowercase words" set to "No").
   2. Lowercase URLs ("lowercase words" set to "Yes").

Every time, I got redirected to the correct post on the correct (second) page of the thread.

Please provide instructions on how to reproduce.

**Comment by lairdshaw** [comment]
Any update on this, @Eldenroot?

**Comment by Eldenroot** [comment]
I cannot reproduce now.. you can close.
