### ISSUE TITLE
UCP-> Alert settings empty

### ISSUE THREAD

**Issue by FMashiro** [MyBBStuff/MyAlerts#192]
As the title states, the settings page on the user control panel is empty.
![image](https://cloud.githubusercontent.com/assets/17700907/16178365/fd8197f8-3645-11e6-89db-fa0207629837.png)

For some reason the modal on the navigation menu is not there anymore as well, and I have a duplicate one on the user dropdown: 
![image](https://cloud.githubusercontent.com/assets/17700907/16178377/4a3794b2-3646-11e6-8ea5-ea3a251a4a73.png)

both redirect to alerts.php and no modal opens whatsoever, I just did a clean install of the plugin taken from master and one from the mybb website, first uninstalled the plugin, then overwrote the files and resintalled again.

**Comment by euantorano** [comment]
Hi, what's in the `alert_types` table in phpMyAdmin?

**Comment by FMashiro** [comment]
This is the table:
![image](https://cloud.githubusercontent.com/assets/17700907/16178528/1e6b8d48-364b-11e6-89c1-2e5678575399.png)
and it's completely empty.

FYI, if it helps, I've just fully uninstalled and reinstalled the plugin and the table was empty before hand

**Comment by euantorano** [comment]
Yep, that's the problem then. Probably the easiest thing to do is manually insert the rows. Run the following SQL query in phpMyAdmin:

```sql
INSERT INTO mybb_alert_types (`code`) VALUES
('rep'),
('pm'),
('buddylist'),
('quoted'),
('post_threadauthor'),
('subscribed_thread');
```

Did you definitely fully uninstall, and not just deactivate? The types get added when installing, rather than activating.

**Comment by FMashiro** [comment]
I definetely uninstalled a few times, it could be that you check if the table exists and have the insert inside the if not exists?

**Comment by euantorano** [comment]
I'll check, but the uninstall should have removed the table anyway.

**Comment by FMashiro** [comment]
so the settings are fixed by inserting the query again, but for some reason, the modal isn't working (it jut doesn't appear at all, not on hover or on click, I'm guessing a JS missing selector or something like that) and the links in alert.php only have the tid and miss the pid needed to jump to the right post

**Comment by euantorano** [comment]
The modal issue is normally caused by an old version of alerts.php without the modal action. Try grabbing the current alerts.php from here on GitHub. The PID issue has been reported a couple of times and I need to look into it.

**Comment by FMashiro** [comment]
I've gotten the most recent master branch, I downloaded it a few hours ago and overwrote all the files
but I'll check again just to be sure

**Comment by FMashiro** [comment]
I've just uploaded the full master download, cloudflare is off, cleared cache, tried incognito mode, no luck... The modal just isn't appearing...

**Comment by euantorano** [comment]
Can you send me a PM on the community forums (or my forums) with a URL, and details for a temporary administrative account? I'll take a look at it after my dinner if so.

**Comment by FMashiro** [comment]
Sent the pm, will look forward to your point of view

**Comment by euantorano** [comment]
Right, it's all sorted. You actually had two links to MyAlerts - one in the header, one in the dropdown. The dropdown one worked and was the one inserted by the plugin. The other link looks to of been manually added, and it was missing the required CSS classes on it. I've moved the one in the dropdown into the menu bar now and it works.

**Comment by FMashiro** [comment]
Awesome, thank you a lot! So if I understand correctly, the problem where it isn't picking up the pid is a known thing and is in the works ?

**Comment by euantorano** [comment]
Yeah, I'm not sure what the problem is yet, but there have been a few reports about it.

**Comment by FMashiro** [comment]
I've fixed my version.
For some godforsaken reason "<a name="pid{$post['pid']}" id="pid{$post['pid']}"></a>" was removed from each post in the postbit_classic template.

If any other users have this problem, try going to the postbit->postbit_classic template, and just under "{ignore_bit}" put "<a name="pid{$post['pid']}" id="pid{$post['pid']}"></a>" in the line right under it.
you can see if it's missing by diff to original instead of editing or reverting! 

Thanks a lot for helping man, appreciate it!

**Comment by FMashiro** [comment]
I just remember, idk why but mentioning a user doesn't give an alert. Everything else does, it's just the mentioning part that doesn't give an alert. Any idea why that could be?

**Comment by euantorano** [comment]
Do you mean like an "@<user>" mention? If so, you'd need another plugin to do that, as MyAlerts doesn't have that built in. There are a few plugins that hook into MyAlerts that do it though.

**Comment by FMashiro** [comment]
Alright, I guess that isn't your problem :) I got it to work just now, thanks for everything!
