### ISSUE TITLE
Change private_do_send_end hook to datahandler_pm_insert or similar

### ISSUE THREAD

**Issue by Shade-** [MyBBStuff/MyAlerts#193]
Hi Euan, I know you might be busier on something else as I am busy too, but here's a possible enhancement for the next minor update. private_do_send_end hook which is used to generate the PM alert should be changed with datahandler_pm_insert or something similar found in the pmhandler (reported by Brenda [here](http://www.mybboost.com/thread-myalerts-pm-support-password-empty)). Otherwise, third party plugins sending PMs will not generate an alert.

This is not top priority, and I have not had a look at MyAlerts current implementation so I don't know how hard would it be to change the logic, but I'd just leave it here. If only I got some spare time I would open a PR but unfortunately I have not.

**Comment by euantorano** [comment]
Yeah, this is one of those tasks that has been on my “to fix” list for a while. I’ll need to try and find some time to look at it.
