### ISSUE TITLE
Titles that have been edited, do not update on unread alerts

### ISSUE THREAD

**Issue by thelovelyone** [MyBBStuff/MyAlerts#195]
E.g. user17 creates a thread called "Test123". Someone quotes user17 in "Test123" and user17 hasn't checked his alerts yet and now an admin edits the thread title to "Test444" and when now user17 does check his alerts, he'll still see "Test123" instead of "Test444". 

However when he is quotes again, it does show "Test444", so its only for unread alerts.

Its not a big thing and there are far more significant improvements i'd like to see but its an issue eventually and if its not difficult to fix, you might consider it for the next update.

Thanks.

**Comment by euantorano** [comment]
Yes, this is a known issue and would require a couple of changes. It's not really a big problem as you said.
