### ISSUE TITLE
Hover dropdown alerts

### ISSUE THREAD

**Issue by KingLinux01** [MyBBStuff/MyAlerts#196]
How do I add on hover have it drop down my alerts?

**Comment by euantorano** [comment]
Hi,

This would require a number of JavaScript edits to get it to work along with template edits. I'm afraid I don't provide support for these kind of large changes as it would take too much time.

**Comment by KingLinux01** [comment]
Ok, Maybe when I fingure more JavaScript, html, and css I will try to do it.
