### ISSUE TITLE
Is it possible to change the alert number colour when there is a new alert?

### ISSUE THREAD

**Issue by LewisHolt** [MyBBStuff/MyAlerts#199]
Right now its Alerts (0) in white and when it gets a notification it's still white. 

How would I change it so that when there's a new alert it would change to a green number?

It would make it more visible.

**Comment by euantorano** [comment]
Hi,

This has been asked on the forum several times now (and answered). You can do so using the CSS class `.alerts--new`, with some CSS like the following:

```css
.alerts--new a {
    color: red;
}
```

**Comment by LewisHolt** [comment]
Doesn't seem to work for me.  I've put the css into global.css but the number remains white, even hard refreshed.

**Comment by euantorano** [comment]
You might need to add !important, depending on your theme:

```css
.alerts--new a {
    color: red !important;
}
```

This is also assuming you haven't changed the MyAlerts templates at all.

**Comment by LewisHolt** [comment]
I modified the myalerts_headericon to this 
`<span class="alerts {$newAlertsIndicator}">({$mybb->user['unreadAlerts']})</span>` since I didn't want the modal. `My header_welcomeblock_member is this 
`<a href="{$mybb->settings['bburl']}/alerts.php"><div class ="topbarbutton"><i class="fa fa-bell" aria-hidden="true"></i> Notifications {$myalerts_headericon}</div></a>`

I've also tried !important but it isn't making any effect.

**Comment by euantorano** [comment]
So you've got rid of the link? That would be why it doesn't work. Try this:

```css
.alerts--new {
    color: red !important;
}
```

**Comment by LewisHolt** [comment]
I've set it to redirect to the alerts.php page in the header_welcomeblock_member template. 

Tried the css code you suggested and no such luck. When inspect elemented it doesn't look like any CSS is reaching the alert number.

**Comment by euantorano** [comment]
Can you send me your URL and details for a temporary admin account? Probably much easier that way.
