### ISSUE TITLE
urlencode() array Problem at ModCP 

### ISSUE THREAD

**Issue by codeinstein** [MyBBStuff/MyAlerts#200]
I was testing my forum(Running latest MyBB) for vulnerabilities and I came up with this issue:
When you go to Moderator CP and announcements:
Ex: https://forumsite.com/modcp.php?action=announcements
And insert "[]" between "action" and "=" , the following warning on the picture occurs. 
![screen shot 2017-04-14 at 00 55 08](https://cloud.githubusercontent.com/assets/20325698/25025997/3720fcea-20ad-11e7-986c-6686437dd5c5.png)

**Comment by euantorano** [comment]
Try using the current version of the code from GitHub, as I think I fixed this a few months ago. The version on the MyBB mods site is vastly out of date.
