### ISSUE TITLE
Inverted colors on header icon

### ISSUE THREAD

**Issue by ZeroAnon** [MyBBStuff/MyAlerts#201]
The header icon is inverted in color, chainging the class only makes it unclickable. The button is white until hovered over then it turns blue, it needs to be the opposite. Is there a bit of CSS for this?

**Comment by euantorano** [comment]
Hi,

Yes, there [are several classes](https://github.com/MyBBStuff/MyAlerts/blob/master/inc/plugins/MybbStuff/MyAlerts/templates/headericon.html#L1) used. You can also edit the template `myalerts_headericon` in ACP > Templates & Style > Templates > _Your Theme_ > MyAlerts Templates.

The classes in use are:

- `alerts` - always used on the wrapping `<li>`
- `alerts--new` - used when there are unread alerts
