### ISSUE TITLE
<Span> Code showing

### ISSUE THREAD

**Issue by thunderclap82** [MyBBStuff/MyAlerts#202]
After upgrading to MyBB 1.8.12, the <span> code is showing in the MyAlerts popup.

![screen shot 2017-06-16 at 12 58 03 pm](https://user-images.githubusercontent.com/18503620/27238923-685bd834-5294-11e7-84f5-de3486e1e9a6.png)

**Comment by thunderclap82** [comment]
Disregard. I saw this was addressed in the MyBB forum with a link to changed code here. https://github.com/MyBBStuff/MyAlerts/commit/31b2039311174391952806aa536eba3dfaba8089

**Comment by euantorano** [comment]
Yep, was fixed in https://github.com/MyBBStuff/MyAlerts/commit/31b2039311174391952806aa536eba3dfaba8089
