### ISSUE TITLE
Bug connected with replying by guest

### ISSUE THREAD

**Issue by Cyber52** [MyBBStuff/MyAlerts#203]
I have a one section on my forum wchich is directed for guest and there is a bit problem with replying by them. Every other group can write replies besides guests. This is what they see after clicking the submit button: https://i.imgur.com/ntZq2By.jpg

This problem appears only in this section for guests. They can create a new thread but can't writing replies. I appreciate every help with that.

**Comment by euantorano** [comment]
Hi,

Are you using the current code from GitHub?

**Comment by Cyber52** [comment]
I downloaded it from this webstire https://community.mybb.com/mods.php?action=view&pid=518 and I'm using MyAlerts ver. 2.0.2

**Comment by euantorano** [comment]
Hi,

The code there is out of date. Please use the download from here: https://github.com/MyBBStuff/MyAlerts/archive/master.zip

**Comment by Cyber52** [comment]
I think It works fine now. Thanks

**Comment by Cyber52** [comment]
Unfortunately the problem still exist. Now this is what it shows for users http://imgur.com/a/raoOn

**Comment by euantorano** [comment]
Interesting. I'll have a look into it.

**Comment by lairdshaw** [comment]
Hi @Cyber52  and @euantorano,

Just wondering whether either of you got to the bottom of this one or at least found a recipe for replication. Looking at the second image, it seems that the error occurred in the DVZ Mentions plugin, however, the file in which the error occurred - `inc/plugins/dvz_mentions/alerts/alerts.class.php` - no longer exists in the current version (1.0.6) of DVZ Mentions - so I can't even look up the relevant line. Maybe the bug has been resolved by now? If not, @Cyber52, please provide details so we can fix this for the upcoming release.

**Comment by euantorano** [comment]
Looking back at the screenshots, the error definitely seemed to be in the DVZ mentions plugin rather than MyAlerts itself, so I think this issue can be closed.

**Comment by lairdshaw** [comment]
Done!
