### ISSUE TITLE
Bell icon not showing up while using a theme

### ISSUE THREAD

**Issue by Axlnh** [MyBBStuff/MyAlerts#205]
Hey, first thanks for this good plugin :+1: 
My only problem is that the bell icon isn't showing up when using a theme : Flatty

any idea where I can modify this please ? I searched for like a week and nothing worked for me.

Thanks in advance

**Comment by euantorano** [comment]
Would you mind sending me a PM on the forum (user: Euan T) with your URL and details for a user account? That way I can look at the theme in action to work out the fix.
