### ISSUE TITLE
Incorrect information on installed alert types due to out-of-sync cache

### ISSUE THREAD

**Issue by Devilshakerz** [MyBBStuff/MyAlerts#206]
`MybbStuff_MyAlerts_AlertTypeManager` is not called in `myalerts_uninstall()` to synchronize the `mybbstuff_myalerts_alert_types` datacache for installed alert types, making the plugin skip alert types upon second installation.
Reproducible when adding or modifying core alert types.

**Comment by euantorano** [comment]
Ah, good catch. That would cause problems for sure.
