### ISSUE TITLE
No alert types other than "Likes" (have integrated with the "Thank You/Like System" plugin)

### ISSUE THREAD

**Issue by lairdshaw** [MyBBStuff/MyAlerts#210]
Hi,

Have installed both this plugin (latest version from GitHub as of today) and the "Thank You/Like System" plugin (also latest version from GitHub as of about a week ago) to a MyBB forum version 1.8.12.

No alert types are available at admin/index.php?module=config-myalerts_alert_types other than "tyl" - the type added by the "Thank You/Like System" plugin. When I deactivate the "Thank You/Like System" plugin, no alert types whatsoever are available.

When activated, the "Thank You/Like System" reports: "Thank You/Like System and MyAlerts were integrated successfully!"

Does anybody know of a fix for this problem? Our members would really like to be notified of the usual events on top of likes.

**Comment by euantorano** [comment]
Can you check the `mybb_alert_types` table to see if there's anything in there? If not, you can add the alert types with the following query:

```
INSERT INTO `mybb_alert_types` (`code`, `enabled`, `can_be_user_disabled`) VALUES ('rep', 1, 0), ('pm', 1, 0), ('buddylist', 1, 0), ('quoted', 1, 0), ('post_threadauthor', 1, 0), ('subscribed_thread', 1, 0); 
```

There was a bug in old versions that when you uninstalled the plugin it wouldn't clear the cache properly, which was fixed here: https://github.com/MyBBStuff/MyAlerts/commit/2cd8e128db079a78d4bd59396abec1a378f97eab

**Comment by lairdshaw** [comment]
Super! That's solved the problem!

There was nothing in the mybb_alert_types table other than the 'tyl' type. After adding the new types with your supplied insert statement, and then reloading the "mybbstuff_myalerts_alert_types" cache in the Admin CP, now the other alert types are displaying both in the Admin and User CPs.

Thank you so much for your prompt attention to this, and kudos for creating this valuable plugin which adds so much value to our forum.
