### ISSUE TITLE
How does this plugin place its code snippet?

### ISSUE THREAD

**Issue by iagovar** [MyBBStuff/MyAlerts#221]
Hi, I'm modifying a design here: http://quecarallo.net/mybb/

I installed MyAlerts to see how does it behave, but the code snippet is not properly placed. I tried to search on the templates where does MyAlert put its snippet but I didn't have success.

¿Is is possible to move the snippet into the div I want? 

https://i.imgur.com/OBI2yLl.png

**Comment by euantorano** [comment]
Hi,

The variable is inserted into the `header_welcomeblock_member` template. You can edit that template to move the `{$myalerts_headericon}` variable anywhere that you want it.
