### ISSUE TITLE
Errors on PHP7

### ISSUE THREAD

**Issue by Xayaan** [MyBBStuff/MyAlerts#222]
http://prntscr.com/i97thp

MyBB version :  1.8.14 
PHP version : 7.0.27

**Comment by WildcardSearch** [comment]
This issue here is that you haven't uploaded all of the files. This repo has dependencies that are not included. IIRC you must download the version from the mods site. Is that correct, @euantorano?

**Comment by euantorano** [comment]
The project isn’t public on the mods site, as it proved to be a pain to keep up to date. Instead, see the instructions available here: https://community.mybb.com/thread-171301-post-1160744.html#pid1160744

**Comment by Xayaan** [comment]
Ah.. Sorry for being so ignorant. 

Thank you!
