### ISSUE TITLE
Save Alerts?

### ISSUE THREAD

**Issue by K0NIG** [MyBBStuff/MyAlerts#223]
I saw a long time ago you posted on the [Mybb Forum](https://community.mybb.com/thread-171301-post-1250620.html?highlight=save+alerts#pid1250620) saying you'd like to add the capability to mark alerts as read/seen and save them for later viewing.

This was back in 2016 and I was interested in inquiring on whether you're still planning on implementing these changes. Thanks!

**Comment by euantorano** [comment]
The way that the plugin currently works is that any alerts you view in the modal from the header are marked read, but they aren’t deleted. You can then view all alerts from the User CP. 

I don’t have any plans further than that at the minute for saving alerts or anything.

**Comment by labrocca** [comment]
Is it possible to add a "mark all read" in the modal?  The modal also seems to show read alerts even if you close it and open it again or change pages.  Why would it show already read alerts?  And it's an issue where I have 20 alerts and set modal to show 5 but maybe I marked the recent ones read but unless I go into the full alerts.php page I don't see the rest of them.  Plus the CSS for read/unread on that page is bad.  It does not differentiate.  That I can change myself though.

**Comment by euantorano** [comment]
Yeah, it should be easy enough to add it to the template, I can add it myself for a future version. 

The modal shows all alerts to act like FaceBook, but I agree it isn’t the best approach. It should instead either only show unread, or show unread alerts at the top of the list. I’m not sure which would be the better option?

The new version I’m working on that I linked to on the forum should help sort this kind of issue. I’m going to create a thread on the forum later tonight explaining what changes I’m making, what I’m trying to fix with it, etc.

**Comment by labrocca** [comment]
Only show unread with the link (already there) to all alerts.  On the modal change "Recent Alerts" to "Unread Alerts" so it's clear.

**Comment by euantorano** [comment]
Yep that sounds like the best approach, thanks. It might be a good idea to add a filter to the full page to allow filtering to show only unread and all alerts.

**Comment by labrocca** [comment]
The css should be fine to distinguish.   You should fix that.  I think you have the CSS in the TR for alerts but it's not marking it.  It's the same CSS issues in the modal too. 

And you should consider having a defined alert in header color by default.  I noticed others were confused about how to change that text color as well.

**Comment by K0NIG** [comment]
The alerts disappear once you click on them though. I guess one solution is to just not click on them to save them, but it's not very intuitive since you'd need to go fish up the thread yourself .

I agree with labrocca's suggestion as well.

**Comment by StureZz** [comment]
sa

**Comment by Eldenroot** [comment]
Mark as unread would fix this? @lairdshaw

**Comment by lairdshaw** [comment]
Seems like a good solution, @Eldenroot. Against read alerts, the tick character with tooltip "Mark as Read" could change to an appropriate symbol (maybe ⟲ but maybe we could find something better) with tooltip "Mark as Unread".

**Comment by Eldenroot** [comment]
#316

**Comment by Eldenroot** [comment]
Maybe for future - add a new "favorite" button, it will change the background color and make the notificatiom.unread. you can also filter these type of alert
