### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by wyatt-herkamp** [MyBBStuff/MyAlerts#224]
MyAlerts (1.05)
A simple notifications/alerts system for MyBB

To enable all alerts for existing users, please click here: Run Script. This script may take a while for large boards. If you have many users, it's advised to run this via the PHP CLI.
Created by euantor
How do I fix this. That script ends with

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1146 - Table 'mybb.mybb_alert_setting_values' doesn't exist
Query:
DELETE FROM mybb_alert_setting_values

**Comment by Eldenroot** [comment]
@lairdshaw - I think this is a not valid issue, it is 5 years old, v1.x branch. Close it :)

**Comment by wyatt-herkamp** [comment]
Wow this is old. I haven't even thought of this software in years. 😂😂. 

Issue is closed now though.
