### ISSUE TITLE
Modal return link with an `action` parameter overrides action

### ISSUE THREAD

**Issue by euantorano** [MyBBStuff/MyAlerts#226]
The `alerts.php?action=modal` page takes a `ret_link` parameter to redirect to a return page. If the `ret_link` contains an `action` parameter, the `action=modal` is overwritten as a URL such as `https://www.mybbstuff.com/alerts.php?action=modal&ret_link=https://www.mybbstuff.com/misc.php?hid=5&action=help` is the result.

The return link should be built from the HTTP referrer header instead, or the `ret_link` should be encoded to prevent this kind of issue.

**Comment by lairdshaw** [comment]
It looks like this was fixed by #233.
