### ISSUE TITLE
Not download correctly

### ISSUE THREAD

**Issue by caygri** [MyBBStuff/MyAlerts#228]
Hello i download all zip but missing all file inside /mybb/inc/plugins/MybbStuff/Core/ClassLoader.php

**Comment by euantorano** [comment]
Hi,

The zip on GitHub doesn't include that file, but you can download it here: https://github.com/MyBBStuff/Plugins.Core/blob/master/ClassLoader.php

The zip releases I post on the community forum do contain this file.
