### ISSUE TITLE
Add user profile link in alerts

### ISSUE THREAD

**Issue by ghost** [MyBBStuff/MyAlerts#229]
I hope you add link to the user profile when you click on username. I know we can click profile using image but it will be proper if we are redirected to profile when we click username. :)

https://community.mybb.com/thread-171301-post-1307331.html#pid1307331

**Comment by Eldenroot** [comment]
@lairdshaw what about this one together with #145

**Comment by lairdshaw** [comment]
@Eldenroot, to me, the changes to the code that would need to be considered and then implemented are not worth the gain in functionality. To me, it seems acceptable to be able to click on avatars. If you or somebody else has an opposite weighing of value though, then I'm happy for you/them to implement this feature.

**Comment by lairdshaw** [comment]
On further reflection, I think that adding this feature would - in addition to my sentiments above - lead to too much confusion. The entire alert message is currently a link. Splitting out _within_ that link a separate link for the username could easily lead users to conflate the two links, and accidentally click on the username link when they intended to click on the alert link. I think that this issue should simply be closed.

**Comment by Eldenroot** [comment]
Please, close this one :)
