### ISSUE TITLE
Recognize when edit

### ISSUE THREAD

**Issue by Shade-** [MyBBStuff/MyAlerts#23]
Hi euan,
I succeeded into making the quoting function work together with my own edits thanks to frostschutz help. Now I'm testing it and I have a suggestion for you: it would be great if notifications would be sent also when an user modifies his own post (in general, when a post is being edited) and adds another quoted message.

**Comment by euantorano** [comment]
I know this has been around a while, but I'm setting a 2.1.0 milestone to get this fixed for that release :)
