### ISSUE TITLE
Typo In Modal Content Template

### ISSUE THREAD

**Issue by WildcardSearch** [MyBBStuff/MyAlerts#240]
In `myalerts_modal_content`, another `<tr/>` appears after `<tbody/>`is closed:

https://github.com/MyBBStuff/MyAlerts/blob/ab527adcf9b75c16baa63afb4a1efa7375e349d6/inc/plugins/MybbStuff/MyAlerts/templates/modal_content.html#L10-L14

**Comment by Eldenroot** [comment]
@lairdshaw this one for 2.1.0
