### ISSUE TITLE
I dont get alerts for new PMs

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#241]
With latest master GitHub version I dont get notifications for new PMs :(

**Comment by WildcardSearch** [comment]
@Eldenroot I use this version: https://github.com/euantor/MyAlerts/archive/current.zip

Everything seems to be working correctly (just did a test before posting)

**Comment by Eldenroot** [comment]
Hmm, thats super weird. Tested twice, tried uni stall and install again, without success

**Comment by Eldenroot** [comment]
@WildcardSearch - I know exactly how to debug - disable all alerts in your UCP and then enable only alerts for new PMs -> alerts wont work! But when you enable then any of disabled alerts and save settings -> alerts are displayed for PMs

**Comment by WildcardSearch** [comment]
I want to stress that the link I posted is not the same as the master branch. I would think it should be, but it isn't. The version under current is the only version I can use without issue. @Eldenroot

**Comment by WildcardSearch** [comment]
I just tested and there is something odd going on, for sure.

Following Eldenroot's steps to reproduce confirms that no alert is sent under those conditions. The weird part is that an alert row ***is*** being created, but when viewing alerts nothing is shown even when marked unread:

![Screen Cap Adminer](https://screenshotscdn.firefoxusercontent.com/images/0651d3d9-7a78-4f2a-9c91-ae7bdc589f58.png)

**Comment by euantorano** [comment]
What does the users row in the users table?

**Comment by WildcardSearch** [comment]
![](https://screenshotscdn.firefoxusercontent.com/images/4dbeb8b9-a8ec-419e-9f79-f34f4e8e64eb.png)

**Comment by WildcardSearch** [comment]
Another piece of information, @euantorano.

I have a custom AJAX refresh on my MyAlerts header icon. At the interval, it reports a new alert (it just checks the db instead of going through MyAlerts system for a quick check), but when I fetch the modal, it shows no alerts.
