### ISSUE TITLE
my_post_key is not defined

### ISSUE THREAD

**Issue by userMacieG** [MyBBStuff/MyAlerts#244]
Hi :)
I have this error on my site:
`myalerts.js:66 Uncaught ReferenceError: my_post_key is not defined
    at myalerts.js:66`
I dont edit plugin files.

**Comment by euantorano** [comment]
Any chance you can provide your URL and details for a test account?

**Comment by userMacieG** [comment]
https://forum.cuddi.pl/ 
login: demo
password: zaq1@WSX

**Comment by userMacieG** [comment]
Btw. I find one mini bug.
I have `mysupport` plugin and if I go to myalerts settings page on usercp in nav links from mysupport stops parse and I see `{mysupport_nav_option}. Its vault of this plugin or mysupport?

**Comment by userMacieG** [comment]
Next thing is if you have contant of author of `MentionMe` you can tell them in his plugin they are missing 2 messages for myalerts.

$l['myalerts_settings_updated'] && $l['myalerts_settings_updated_title']

**Comment by userMacieG** [comment]
You can close this issue.
Its been my vault. I move {$myalerts_js} on top of `var my_post_key = "{$mybb->post_code}";` in `headerinclude`

**Comment by euantorano** [comment]
No problem, and sorry I didn't get a chance to test for you.
