### ISSUE TITLE
Quote does not work propertly and right way to reproduce error.

### ISSUE THREAD

**Issue by WhiteNeo** [MyBBStuff/MyAlerts#245]
I have found this issue and is very strange because this is how to reproduce and with trace of events it supose that have to work fine.

Anyways this is how to reproduce it.

Install the plugin, even in a new environment i have tested with new 1.8.20, with 1.8.19 and 1.8.10.

Create an username with this name John Green

Ok at this point all goes fine.

Go and press quote button in some post that this user have replied.

Now you will see that alert is not recorded, but if you analize the query and see it must work.

However if you use multiquote instead quote yeah it works fine but query and all sentences are the same exactly.

I have changed the query for that instance of code, and use an foreach with users equal to username and more that causes the same effect, at this point i am hands off because i have made multiple tests for i can found this information. But yeah this is the right way to reproduce it and i have seen that other names with whitespaces works but some others do not.

Right now i am testing the latest myalerts version and for now none of names with whitespaces works but only for quote, but multiquote works fine. But it must work because it uses same hook and same pieces of code but there must be some patr of the code that causes this issue.

**Comment by euantorano** [comment]
Yeah, there have been a few reports of issues with quotes over the years but I’ve never managed to track the cause down. I’ll have another look at it this week.

**Comment by WhiteNeo** [comment]
Thanks i am trying to find a way to put the query to work. I have used source mode and more. Only it seems into quick reply works fine and get data. But with newreply into direct reply and quote with some usernames do not achieve array data. Query it's fine i have runed into phpmyadmin and review both cases but for some weird reason into reply quoting the post or a plenty of them data is fine but into fetch array data was losen for some strange reason. I have tryed multiple instances of code but all cases go throught same result. Anyways i will try another ways but i have added num_rows to see if query gets results and nope, with multiquote it gets right values and rows, but reply button to quote post anytime gets results into query but no rows :o

And with normal usernames works perfect so it is more strange hahaha. If i use normal names both cases works fine multiquote and quote buttons.

**Comment by WhiteNeo** [comment]
Ok and i have found the problem, it cames with sceditor because regex does not work propertly for some reason and data are not taken in right instances for usernames within special chars, however i have found a temporary solution, Using Rin Editor solves the issues, because it adds the complete data into quotations.

Sceditor loads with only usernames, but this one takes anyways the current user data but anyways i have tested within source mode before sent and do nothing, but i have tryed Rin Editor to make some testes before test quick advanced editor. But yeah it works fine with this, so i will continue doins more tests to gave you more information if posible :) Anyways thanks for all your time ;)

**Comment by euantorano** [comment]
Great, yet more SCEditor problems :(

We’re looking at possibly upgrading to the newest SCEditor 2.0 in MyBB 1.8.21 which might break things in a different way too :)

**Comment by WhiteNeo** [comment]
No problem :) i will try to add into js for sceditor the missing parts for quote i think that should solve the issues aswell. And if i catch anything i will let you know :) thanks for your effort and time, you do an excellent and amazing job always :)

**Comment by WhiteNeo** [comment]
Ok i have maded some few tests but woth the old pr and does not work for sceditor.

Now i will try the latest mybb 1.8.20 released package with, and without changes of source js codes and let you know.

I have seen that you are very bussy with mybb project so good luck and thanks as always for your time :)

**Comment by lairdshaw** [comment]
@andrewjs18 recently raised this as a problem on his board, and I looked into it independently, not being aware of this existing issue. The problem seems to be that ordinary spaces are in various circumstances - at least some potentially due to SCEditor - converted into non-breaking spaces. Converting them back again before running the DB query based on quoted username resolves the issue. @WhiteNeo has confirmed in Discord chat that the fix works, and, as far as I know, it worked for @andrewjs18 too, albeit that quote alerts are not generated on his board when using Tapatalk (it seems that Tapatalk does not support MyAlerts in general). I'll shortly file a PR with the fix.

**Comment by euantorano** [comment]
I always suspected SCEdtor, as I never managed to replicate these issues in source mode. Thanks for investigating!
