### ISSUE TITLE
Incompatibility with updated ClassLoader?

### ISSUE THREAD

**Issue by kawaii** [MyBBStuff/MyAlerts#249]
```
Warning [2] require_once(/var/www/html/inc/plugins/MybbStuff/CoreClassLoader.php): failed to open stream: No such file or directory - Line: 26 - File: inc/plugins/myalerts.php PHP 7.3.4 (Linux)
Fatal error: require_once(): Failed opening required '/var/www/html/inc/plugins/MybbStuff/CoreClassLoader.php' (include_path='.:/usr/local/lib/php') in /var/www/html/inc/plugins/myalerts.php on line 26
```
When visiting `admin/index.php?module=config-plugins` after uploading the latest version of MyAlerts from GitHub.

**Comment by WildcardSearch** [comment]
@kawaii iirc you have to grab that from here: https://github.com/MyBBStuff/Plugins.Core

**Comment by kawaii** [comment]
@WildcardSearch ah there's actually a new version of the ClassLoader distributed with Euan's more recent plugins (such as `mybb-prometheus` and the updated version of `SimpleLikes` which you can see [here](https://github.com/MyBBStuff/SimpleLikes/blob/fix/postgres-compat-and-update/inc/plugins/MybbStuff/Core/src/ClassLoader.php)). The issue is that MyAlerts needs updating too now to take advantage of it due to the changes in how namespaces are handled. :)

**Comment by WildcardSearch** [comment]
Okay...that error message indicates that the class loader is ***missing***...not the wrong version.

**Comment by kawaii** [comment]
In this case MyAlerts can't even ascertain the correct location of ClassLoader due to the incompatibility, if you read the error message you'll note the `CoreClassLoader.php` reference instead of the usual `Core/ClassLoader.php` indication that it's missing.

**Comment by WildcardSearch** [comment]
Indeed. My curiosity is now satisfied. Thanks.

**Comment by lairdshaw** [comment]
I don't think inclusion is a good idea, because we want people to install the latest version. Notification display could be a good idea because people regularly report white screen errors on the ACP Plugins page which are a result of failing to install PluginLibrary (and/or [Plugins.Core](https://github.com/MyBBStuff/Plugins.Core)).

**Comment by Eldenroot** [comment]
This one wpuld be nice for 2.1.0 @lairdshaw
