### ISSUE TITLE
Delete read alerts link also deletes unread alerts in alert.php

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#260]
As title says - "Delete old alerts" works fine in a modal popup window, but not in the alert.php page - it deletes all the alerts (read and unread).

**Comment by Eldenroot** [comment]
@lairdshaw - is it covered by https://github.com/MyBBStuff/MyAlerts/pull/309 ?

**Comment by lairdshaw** [comment]
I don't know what fixed it nor what caused the original problem, but I can't reproduce it. I *do* notice though that the confirmation message on deleting read alerts from the `alerts.php` page is mistakenly reusing the confirmation message for deletion of *all* alerts, so perhaps that's the source of the confusion?

**Comment by Eldenroot** [comment]
Where? Cannot reproduce?

**Comment by lairdshaw** [comment]
> Where? Cannot reproduce?

https://github.com/MyBBStuff/MyAlerts/blob/8c3c0b23afbb741463f159b36c5631058bb80a26/alerts.php#L294 and https://github.com/MyBBStuff/MyAlerts/blob/8c3c0b23afbb741463f159b36c5631058bb80a26/alerts.php#L300

Both reuse the `myalerts_delete_all` language string, which is set to `'All alerts deleted successfully.'` We need to define and use here a new language string, maybe `myalerts_delete_read`, setting it to something like `'Read alerts deleted successfully.'`

**Comment by Eldenroot** [comment]
I saw these lines but I cannot reproduce on my board - it displays:

Delete ALL notifications
Delete read notifications

Tested url links in UCP and popup modal window...
can you confirm?

**Comment by Eldenroot** [comment]
You are right... valid

**Comment by lairdshaw** [comment]
@Eldenroot, can you please confirm that the original issue is no longer an issue, and if so, can we close this issue?

**Comment by lairdshaw** [comment]
Closed in the absence of confirmation this is still an issue. Feel free to reopen if it is.
