### ISSUE TITLE
Plugins page is blank, cant install.

### ISSUE THREAD

**Issue by enescaglayan** [MyBBStuff/MyAlerts#264]
![Screenshot_2](https://user-images.githubusercontent.com/47847977/69885347-c4693600-12ed-11ea-8c89-c2b41df3a642.png)
I uploaded all files, when i go plugins page this happens. Plugin library 13 is installed and class loader is in mybbstuff/core, i tried 2.0.4 version and master branch it didnt work.

i have these plugins installed and activated:

rin editor, bam announcements, dvz mentions and shoutbox, mybb google seo, and thank you like system myalerts tapatalk support oh also plugin library but it isnt in activated plugins section.

known fix: just delete myalerts.php from plugins folder and wait for the fix.

**Comment by euantorano** [comment]
Can you check your server error log please? A blank page usually indicates an internal server error.

**Comment by enescaglayan** [comment]
Not using mybb anymore, sorry.
