### ISSUE TITLE
MyBB Internal: One or more warnings occurred. Please contact your administrator for assistance.

### ISSUE THREAD

**Issue by djyee** [MyBBStuff/MyAlerts#273]
i got this error when i upload myalerts plugin

File | Line | Function
-- | -- | --
/inc/plugins/myalerts.php | 25 | errorHandler->error
/inc/plugins/myalerts.php | 25 | require_once
/admin/modules/config/plugins.php | 516 | require_once
/admin/index.php | 824 | require

mybb version: 1.8.24

**Comment by euantorano** [comment]
You need to upload the `ClassLoader.php` file [from here](https://github.com/MyBBStuff/Plugins.Core/blob/master/ClassLoader.php) to `inc/plugins/MybbStuff/Core/ClassLoader.php`.
