### ISSUE TITLE
Mark read button (modal/UCP) is not working

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#280]
Delete is working fine.

I made maybe some typo in my addition?

https://github.com/MyBBStuff/MyAlerts/commit/d3aa38763e5d665cad83df76de83bc6d89222bbc

Thank you!

@lairdshaw

**Comment by lairdshaw** [comment]
Probably it's just that the stylesheet's been deleted on MyBB core upgrade (a known bug), in which case the fix is simply to deactivate then reactivate the plugin. Let us know if that doesn't work.

**Comment by Eldenroot** [comment]
Hmm, is there any workaround?

**Comment by lairdshaw** [comment]
That which I referred to as "the fix" is better referred to as "the workaround", so, yep - that *is* the workaround: every time core is upgraded and the install script is run, you need to deactivate then reactivate any plugins whose stylesheets were deleted during that core upgrade process (customised stylesheets aren't deleted).

**Comment by lairdshaw** [comment]
Is this issue resolved, @Eldenroot?
