### ISSUE TITLE
Plugins page goes blank (MyBB 1.8.34)

### ISSUE THREAD

**Issue by Splicho** [MyBBStuff/MyAlerts#295]
Hi,

I downloaded the package and added it to my root directory. But now, after I go to plugins page, the page is blank.

![brave_blKwrIiiIS](https://github.com/MyBBStuff/MyAlerts/assets/4650700/d12a789e-b4f9-4050-9c78-1c48283074ec)

I also executed the SQL File.
I can access the plugin page when I delete the **myalerts.php** file from the plugins folder, guess something is wrong with this file.

Somebody know what's wrong? I am using latest MyBB.

**Comment by lairdshaw** [comment]
See: https://community.mybb.com/thread-238665.html

**Comment by Splicho** [comment]
> See: https://community.mybb.com/thread-238665.html

Oh wow, thank you for the faster answer. Below the output.

![brave_F3w9pO8Uyq](https://github.com/MyBBStuff/MyAlerts/assets/4650700/d5f6c03b-8143-48c7-b65b-46446422cbba)

**Comment by lairdshaw** [comment]
No worries, and, yep, given that output, there are missing dependencies, as mentioned in note 2 at the bottom of the link I shared. See that note or the plugin's README.md for the dependencies you need to install.

**Comment by Splicho** [comment]
> No worries, and, yep, given that output, there are missing dependencies, as mentioned in note 2 at the bottom of the link I shared. See that note or the plugin's README.md for the dependencies you need to install.

Oh wow, thank you! Works now as intended, much love.
