### ISSUE TITLE
Header icon visible on if an alert is available

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#308]
This line https://github.com/MyBBStuff/MyAlerts/blob/master/inc/plugins/myalerts.php#L829 needs a new setting in ACP

Move to a conditional few lines above.

**Comment by lairdshaw** [comment]
If this were to be implemented, I think there should be a setting: "Only display alerts header when unread alerts exist?" or something like that, so those who prefer the current behaviour could keep it. I'm one of them, so I'm not motivated to work on this issue. I'd be happy to help you code it up yourself and submit a PR though.

**Comment by lairdshaw** [comment]
Yep, I understood: I was suggesting that setting as an ACP setting. Some admins might prefer the current behaviour (I'm one who does).

**Comment by lairdshaw** [comment]
Now, I'm not sure that this is a sensible feature even when optional: what if a member has no unread alerts but read alerts that (s)he wants to revisit, but the admin has disabled the header icon? The member would not be able to view those read alerts except by visiting the UCP - which they might not know to do - or manually entering in `alerts.php` - which they almost certainly won't know to do.

Even if it were to be adopted, I see problems with its implementation in PR #318, which I'll write up there shortly.

**Comment by Eldenroot** [comment]
You are right, stupid idea :)
