### ISSUE TITLE
Only unread - button is not visible

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#351]
![image](https://github.com/MyBBStuff/MyAlerts/assets/778890/40e70e9c-1bc0-4144-8515-28ea8a230eb8)

**Comment by lairdshaw** [comment]
What are the contents of your `myalerts_modal_content` template? It should contain this line:
```html
<input type="checkbox" id="unreadOnlyCheckbox" name="unreadOnlyCheckbox" value="1"{$unreadOnlyChecked} /> <label for="unreadOnlyCheckbox">{$lang->myalerts_modal_unread_only}</label>
```
Does it?

**Comment by lairdshaw** [comment]
Are you using the default theme? It looks fine to me on a vanilla installation. If not using the default theme, then apply styling as necessary.
