### ISSUE TITLE
Mark read/unread displays the notification alert link wrongly (counter)

### ISSUE THREAD

**Issue by Eldenroot** [MyBBStuff/MyAlerts#352]
![image](https://github.com/MyBBStuff/MyAlerts/assets/778890/8c76ed6f-f431-4c4b-80a9-b71ed8b28ff6)

**Comment by lairdshaw** [comment]
What are the contents of your `myalerts_headericon` template?

**Comment by Eldenroot** [comment]
`<li class="alerts {$newAlertsIndicator}">
    <a href="{$mybb->settings['bburl']}/alerts.php" class="myalerts" onclick="MyBB.popupWindow('/alerts.php?modal=1&amp;ret_link={$myalerts_return_link}', { fadeDuration: 250, zIndex: (typeof modal_zindex !== 'undefined' ? modal_zindex : 9999) }); return false;">{$lang->myalerts_alerts}
        ({$mybb->user['unreadAlerts']})</a>
</li>`

**Comment by Eldenroot** [comment]
<li class="alerts {$newAlertsIndicator}">
    <a href="{$mybb->settings['bburl']}/alerts.php" class="myalerts" onclick="MyBB.popupWindow('/alerts.php?modal=1&amp;ret_link={$myalerts_return_link}', { fadeDuration: 250, zIndex: (typeof modal_zindex !== 'undefined' ? modal_zindex : 9999) }); return false;">{$lang->myalerts_alerts}
        ({$mybb->user['unreadAlerts']})</a>
</li>

**Comment by lairdshaw** [comment]
Is it fixed if you force-reload the page? I forgot to bump the version of the Javascript file in `<head>`, so your browser might not be loading the most recent version.

**Comment by Eldenroot** [comment]
Relaod page - fixes it. However, it happens only when you mark your alert read and unread again.

**Comment by Eldenroot** [comment]
Btw I use this version with this PR incorporated

https://github.com/MyBBStuff/MyAlerts/pull/350

**Comment by lairdshaw** [comment]
> Relaod page - fixes it. However, it happens only when you mark your alert read and unread again.

Can you please confirm that after force-refreshing, it's still doing this when marking an alert read and unread again? If so, I'll need to take a look at the board on which this is occurring.

**Comment by lairdshaw** [comment]
OK, after checking on your board, the problem seems to be that in your `myalerts_headericon` template, the `({$mybb->user['unreadAlerts']})` occurs on a new line. This violates the expectation of the Javascript, which is that the opening parenthesis of that term is preceded by a space character. My expectation is that adding that preceding space will resolve this issue for you.

Alternatively, in `jscripts/myalerts.js` in the filesystem, find this line:
```php
                    $hdr_alerts_el.html(MybbStuff.MyAlerts.prototype.stripParenAppendix(hdr_alerts_text) + ' (' + unread_count_fmt + ')');
```
and remove the space from the `' ('` string literal.

Perhaps the second is the more general fix we should apply to the plugin?

**Comment by Eldenroot** [comment]
The second solution is better I think.

**Comment by lairdshaw** [comment]
Agreed. I think if we are to implement that fix, then we also should stop prefixing the new alert counts with spaces, so, we'd want to remove the space from the `' ('` string literals on these lines too:
```php
                    $hdr_alerts_el.html(MybbStuff.MyAlerts.prototype.stripParenAppendix(hdr_alerts_text) + ' (' + unread_count_fmt + ')');
```
```php
                    window.document.title = title_bare + ' (' + unread_count_fmt + ')';
```
```php
                        $('.usercp_nav_myalerts').html('<strong>' + sb_text_bare + ' (' + unread_count_fmt + ')</strong>');
```
Can you please test this on your board and make sure it works?

**Comment by Eldenroot** [comment]
Works fine ,thank you!
