### ISSUE TITLE
Issue With Guests Posting (non registered)

### ISSUE THREAD

**Issue by Kolliiman** [MyBBStuff/MyAlerts#360]
[11-May-2024 11:04:10 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getByCode() on bool in /home/public_html/inc/plugins/myalerts.php:843
Stack trace:
#0 /homepublic_html/inc/class_plugins.php(142): myalerts_alert_quoted('')
#1 /homepublic_html/newreply.php(601): pluginSystem->run_hooks(Array)
#2 {main}
  thrown in /home/public_html/inc/plugins/myalerts.php on line 843

wont let them post and causes 
![ssssssssss](https://github.com/MyBBStuff/MyAlerts/assets/68330331/2d7df7a5-25ef-4af1-915b-2040a88f6b01)

**Comment by lairdshaw** [comment]
I can't reproduce this on the latest version of MyAlerts. It looks like you're running an older version. Please upgrade to the latest version, [2.1.0-beta](https://community.mybb.com/mods.php?action=download&pid=518&bid=5335), and test again.

**Comment by Kolliiman** [comment]
[11-May-2024 12:30:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getByCode() on bool in /home/behindhi/public_html/inc/plugins/myalerts.php:891
Stack trace:
#0 /home/behindhi/public_html/inc/class_plugins.php(142): myalerts_alert_post_threadauthor(Object(PostDataHandler))
#1 /home/behindhi/public_html/inc/datahandlers/post.php(1161): pluginSystem->run_hooks(Array, Object(PostDataHandler))
#2 /home/behindhi/public_html/newreply.php(519): PostDataHandler->insert_post()
#3 {main}
  thrown in /home/behindhi/public_html/inc/plugins/myalerts.php on line 891

if the person is registered it dosent cause the error
if the person is not registered and is just a guest making a post it causes that error

**Comment by lairdshaw** [comment]
As I instructed you previously: upgrade to the latest version (2.1.0-beta) and test again.

**Comment by Kolliiman** [comment]
i have

**Comment by lairdshaw** [comment]
It appears not, because line 891 of `inc/plugins/myalerts.php` which is referenced in the error message does not call the referenced `getByCode()` member function. Check the plugin's version number in the ACP plugins module.

**Comment by Kolliiman** [comment]
![ss](https://github.com/MyBBStuff/MyAlerts/assets/68330331/239df2d8-272f-4dba-9044-5ea7d98c2046)

**Comment by lairdshaw** [comment]
Exactly as I wrote: you're running an older version (2.0.2), not the latest version (2.1.0-beta).

**Comment by Kolliiman** [comment]
ok so i had to remove everything manually and it now works thanks and sorry to be a pain :)

**Comment by Kolliiman** [comment]
i now get this when going to the post a guest posted on 

[11-May-2024 12:49:46 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/behindhi/public_html/inc/plugins/myalerts.php:1582
Stack trace:
#0 /home/behindhi/public_html/inc/class_plugins.php(142): myalerts_auto_mark_read_for_thread('')
#1 /home/behindhi/public_html/showthread.php(1124): pluginSystem->run_hooks(Array)
#2 {main}
  thrown in /home/behindhi/public_html/inc/plugins/myalerts.php on line 1582

**Comment by lairdshaw** [comment]
You're probably running into the bug of issue #358. Follow the link there for a solution.

**Comment by Kolliiman** [comment]
Yep all fixed ty 👍
