### ISSUE TITLE
Quote alerts not appearing for users with apostrophes in their usernames

### ISSUE THREAD

**Issue by euantorano** [MyBBStuff/MyAlerts#46]
Reported at WWEForums. The user

```
lil' tit
```

had this issue.

http://wweforums.net/thread-19903.html

Issue doesn't seem to relate to escaping or anything, possible problem with the regex?

**Comment by mrmaiko** [comment]
Hi Euan!

I changed the apostrophes to quote marks and I still get a problem with the alert.

As described here: http://community.mybb.com/thread-192050.html

Might you know what I should change in myalerts.php?

**Comment by euantorano** [comment]
@mrmaiko Unfortunately there's some internal processing done by MyBB/SCEditor that really gets in the way when you use quotes with spaces in the usernames. I've had a glance at the issue in the past but never had time to investigate properly.

I'm going to spend a couple of weekends this month cleaning up issues and adding features to MyAlerts, so I'll have another look at this issue then.

**Comment by mrmaiko** [comment]
Thank you, as always, Euan! You're a real hero  :+1:
