### ISSUE TITLE
New alert type: subscribed threads

### ISSUE THREAD

**Issue by Shade-** [MyBBStuff/MyAlerts#48]
Great work today with 1.04 release! However I've just noticed there isn't this feature request here on GitHub, so I'll add it in case you forgot it: many users - me included - requested a new alert type for when an user posts in a thread you are subscribed to.

I'm quite busy but I can help you writing down at least the first lines of code if you'd like it.

**Comment by euantorano** [comment]
This is now in 2.0.0 :dancer:
