### ISSUE TITLE
Unread alert count in title

### ISSUE THREAD

**Issue by euantorano** [MyBBStuff/MyAlerts#85]
The unread alert count in the page title doesn't seem to appear in version 2.0.0. This should be corrected as it existed in previous versions.

**Comment by Cu8eR** [comment]
@euantorano - it is not working... at least not for me on the fresh mybb

**Comment by euantorano** [comment]
Odd. It was working. Will have another look.

**Comment by Destroy666x** [comment]
The code only works on page enter, the title is never refreshed with AJAX.

**Comment by euantorano** [comment]
It's not meant to be
